branches:
    only:
        - master
        - testTravis

jdk: oraclejdk7

cache: false

sudo: false

env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ANDROID_ABI=armeabi-v7a
    - TERM=dumb

notifications:
   email: false

language: android

install:
   - cd Kassenautomat_DHBW_AS/

android:
  components:

    # The BuildTools version used by your project
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - platform-tools
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - platform-tools


script:
   - ./gradlew build -i
